using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.IO;
using System.Xml;
using System.Data;
using ProjectV1.model;

namespace ProjectV1.Units
{
    class FileIO
    {
       

        loginclasse user = new loginclasse();

        public string filePath = Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments) + "\\data.xml"; // This is the path of MyDocuments folder of your pc
        
        // creating the file
        public bool Exists(String path)
        {
            bool result = false;
            try
            {
                if (File.Exists(path))
                {
                    result = true;
                }
                else
                {
                    XmlDocument doc = new XmlDocument();
                    XmlElement xmlelement = doc.CreateElement("", "account", "");
                    doc.AppendChild(xmlelement);
                    XmlElement xmlelement1 = doc.CreateElement("", "user", "");
                    xmlelement.AppendChild(xmlelement1);
                    XmlElement xmlelement2 = doc.CreateElement("", "pasword", "");
                    xmlelement.AppendChild(xmlelement2);
                    XmlElement xmlelement3 = doc.CreateElement("", "type", "");
                    xmlelement.AppendChild(xmlelement3);
                    doc.Save(path);
                    result = true;
                }
            }
            catch
            {
                result = false;
            }
            return result;
        }


        //-------------------Getting the xml data from creating file ---

        public loginclasse getXmldata()
        {
            DataSet ds = new DataSet();
            loginclasse user = new loginclasse();
            try
            {
                if (Exists(filePath))
                {
                    ds.Clear();
                    ds.ReadXml(filePath);
                    int table = Convert.ToInt32(ds.Tables.Count);
                    for (int i = 0; i < table; i++)
                    {
                        user.User = ds.Tables[i].Rows[0][0].ToString();
                        user.Pasword = ds.Tables[i].Rows[0][1].ToString();
                        user.Type = ds.Tables[i].Rows[0][2].ToString();
                    }
                    return user;
                }
                else
                {
                    return null;
                }
            }
            catch 
            {

               
            }
            return user;
        }
        //------------------- insert the data into created xml file-------------
        public void writeXml(loginclasse user)
        {
          
         
            XmlWriterSettings settings = new XmlWriterSettings();
            settings.Indent = true;
            settings.OmitXmlDeclaration = true;
            settings.NewLineOnAttributes = true;
            XmlWriter writer = XmlWriter.Create(filePath, settings);

            writer.WriteStartDocument();

            writer.WriteComment("This file is generated by the program.");

            writer.WriteStartElement("Users");
            writer.WriteStartElement("user");
            writer.WriteElementString("username", user.User);
            writer.WriteElementString("password", user.Pasword);
            writer.WriteElementString("type", user.Type);
            writer.WriteEndElement();
            writer.WriteEndElement();
            writer.WriteEndDocument();
            writer.Flush();
            writer.Close();
          
        }
    }
}